INSERT INTO meals(strMeal,strDrinkAlternate,strCategory,strArea,strInstructions,strMealThumb,strTags,strYoutube,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient16,strIngredient17,strIngredient18,strIngredient19,strIngredient20,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure16,strMeasure17,strMeasure18,strMeasure19,strMeasure20,strSource,strImageSource,strCreativeCommonsConfirmed,dateModified) VALUES ('Apple & Blackberry Crumble',NULL,'Dessert','British','Heat oven to 190C/170C fan/gas 5. Tip the flour and sugar into a large bowl. Add the butter, then rub into the flour using your fingertips to make a light breadcrumb texture. Do not overwork it or the crumble will become heavy. Sprinkle the mixture evenly over a baking sheet and bake for 15 mins or until lightly coloured.
Meanwhile, for the compote, peel, core and cut the apples into 2cm dice. Put the butter and sugar in a medium saucepan and melt together over a medium heat. Cook for 3 mins until the mixture turns to a light caramel. Stir in the apples and cook for 3 mins. Add the blackberries and cinnamon, and cook for 3 mins more. Cover, remove from the heat, then leave for 2-3 mins to continue cooking in the warmth of the pan.
To serve, spoon the warm fruit into an ovenproof gratin dish, top with the crumble mix, then reheat in the oven for 5-10 mins. Serve with vanilla ice cream.','https://www.themealdb.com/images/media/meals/xvsurr1511719182.jpg','Pudding','https://www.youtube.com/watch?v=4vhcOwVBDO4','Plain Flour','Caster Sugar','Butter','Braeburn Apples','Butter','Demerara Sugar','Blackberrys','Cinnamon','Ice Cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'120g','60g','60g','300g','30g','30g','120g','¼ teaspoon','to serve',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'https://www.bbcgoodfood.com/recipes/778642/apple-and-blackberry-crumble',NULL,NULL,NULL);
INSERT INTO meals(strMeal,strDrinkAlternate,strCategory,strArea,strInstructions,strMealThumb,strTags,strYoutube,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient16,strIngredient17,strIngredient18,strIngredient19,strIngredient20,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure16,strMeasure17,strMeasure18,strMeasure19,strMeasure20,strSource,strImageSource,strCreativeCommonsConfirmed,dateModified) VALUES ('Apam balik',NULL,'Dessert','Malaysian','Mix milk, oil and egg together. Sift flour, baking powder and salt into the mixture. Stir well until all ingredients are combined evenly.

Spread some batter onto the pan. Spread a thin layer of batter to the side of the pan. Cover the pan for 30-60 seconds until small air bubbles appear.

Add butter, cream corn, crushed peanuts and sugar onto the pancake. Fold the pancake into half once the bottom surface is browned.

Cut into wedges and best eaten when it is warm.','https://www.themealdb.com/images/media/meals/adxcbq1619787919.jpg',NULL,'https://www.youtube.com/watch?v=6R8ffRRJcrg','Milk','Oil','Eggs','Flour','Baking Powder','Salt','Unsalted Butter','Sugar','Peanut Butter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'200ml','60ml','2','1600g','3 tsp','1/2 tsp','25g','45g','3 tbs',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'https://www.nyonyacooking.com/recipes/apam-balik~SJ5WuvsDf9WQ',NULL,NULL,NULL);
INSERT INTO meals(strMeal,strDrinkAlternate,strCategory,strArea,strInstructions,strMealThumb,strTags,strYoutube,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient16,strIngredient17,strIngredient18,strIngredient19,strIngredient20,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure16,strMeasure17,strMeasure18,strMeasure19,strMeasure20,strSource,strImageSource,strCreativeCommonsConfirmed,dateModified) VALUES ( 'Ayam Percik',NULL,'Chicken','Malaysian','In a blender, add the ingredients for the spice paste and blend until smooth.
Over medium heat, pour the spice paste in a skillet or pan and fry for 10 minutes until fragrant. Add water or oil 1 tablespoon at a time if the paste becomes too dry. Don''t burn the paste. Lower the fire slightly if needed.
Add the cloves, cardamom, tamarind pulp, coconut milk, water, sugar and salt. Turn the heat up and bring the mixture to boil. Turn the heat to medium low and simmer for 10 minutes. Stir occasionally. It will reduce slightly. This is the marinade/sauce, so taste and adjust seasoning if necessary. Don''t worry if it''s slightly bitter. It will go away when roasting.
When the marinade/sauce has cooled, pour everything over the chicken and marinate overnight to two days.
Preheat the oven to 425 F.
Remove the chicken from the marinade. Spoon the marinade onto a greased (or aluminum lined) baking sheet. Lay the chicken on top of the sauce (make sure the chicken covers the sauce and the sauce isn''t exposed or it''ll burn) and spread the remaining marinade on the chicken. Roast for 35-45 minutes or until internal temp of the thickest part of chicken is at least 175 F.
Let chicken rest for 5 minutes. Brush the chicken with some of the oil. Serve chicken with the sauce over steamed rice (or coconut rice).','https://www.themealdb.com/images/media/meals/020z181619788503.jpg',NULL,'https://www.youtube.com/watch?v=9ytR28QK6I8','Chicken Thighs','Challots','Ginger','Garlic Clove','Cayenne Pepper','Turmeric','Cumin','Coriander','Fennel','Tamarind Paste','Coconut Milk','Sugar','Water',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'6','16','1 1/2','6','8','2 tbs','1 1/2','1 1/2','1 1/2','2 tbs','1 can','1 tsp','1 cup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'http://www.curiousnut.com/roasted-spiced-chicken-ayam-percik/',NULL,NULL,NULL);


INSERT INTO meals(strMeal,strDrinkAlternate,strCategory,strArea,strInstructions,strMealThumb,strTags,strYoutube,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient16,strIngredient17,strIngredient18,strIngredient19,strIngredient20,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure16,strMeasure17,strMeasure18,strMeasure19,strMeasure20,strSource,strImageSource,strCreativeCommonsConfirmed,dateModified) VALUES ('Bakewell tart',NULL,'Dessert','British','To make the pastry, measure the flour into a bowl and rub in the butter with your fingertips until the mixture resembles fine breadcrumbs. Add the water, mixing to form a soft dough.
Roll out the dough on a lightly floured work surface and use to line a 20cm/8in flan tin. Leave in the fridge to chill for 30 minutes.
Preheat the oven to 200C/400F/Gas 6 (180C fan).
Line the pastry case with foil and fill with baking beans. Bake blind for about 15 minutes, then remove the beans and foil and cook for a further five minutes to dry out the base.
For the filing, spread the base of the flan generously with raspberry jam.
Melt the butter in a pan, take off the heat and then stir in the sugar. Add ground almonds, egg and almond extract. Pour into the flan tin and sprinkle over the flaked almonds.
Bake for about 35 minutes. If the almonds seem to be browning too quickly, cover the tart loosely with foil to prevent them burning.','https://www.themealdb.com/images/media/meals/wyrqqq1468233628.jpg','Tart,Baking,Alcoholic','https://www.youtube.com/watch?v=1ahpSTf_Pvk','plain flour','chilled butter','cold water','raspberry jam','butter','caster sugar','ground almonds','free-range egg, beaten','almond extract','flaked almonds',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'175g/6oz','75g/2½oz','2-3 tbsp','1 tbsp','125g/4½oz','125g/4½oz','125g/4½oz','1','½ tsp','50g/1¾oz',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO meals(strMeal,strDrinkAlternate,strCategory,strArea,strInstructions,strMealThumb,strTags,strYoutube,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient16,strIngredient17,strIngredient18,strIngredient19,strIngredient20,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure16,strMeasure17,strMeasure18,strMeasure19,strMeasure20,strSource,strImageSource,strCreativeCommonsConfirmed,dateModified) VALUES ('Bread and Butter Pudding',NULL,'Dessert','British','Grease a 1 litre/2 pint pie dish with butter.
Cut the crusts off the bread. Spread each slice with on one side with butter, then cut into triangles.
Arrange a layer of bread, buttered-side up, in the bottom of the dish, then add a layer of sultanas. Sprinkle with a little cinnamon, then repeat the layers of bread and sultanas, sprinkling with cinnamon, until you have used up all of the bread. Finish with a layer of bread, then set aside.
Gently warm the milk and cream in a pan over a low heat to scalding point. Don''t let it boil.
Crack the eggs into a bowl, add three quarters of the sugar and lightly whisk until pale.
Add the warm milk and cream mixture and stir well, then strain the custard into a bowl.
Pour the custard over the prepared bread layers and sprinkle with nutmeg and the remaining sugar and leave to stand for 30 minutes.
Preheat the oven to 180C/355F/Gas 4.
Place the dish into the oven and bake for 30-40 minutes, or until the custard has set and the top is golden-brown.','https://www.themealdb.com/images/media/meals/xqwwpy1483908697.jpg','Pudding,Brunch','https://www.youtube.com/watch?v=Vz5W1-BmOE4','butter','bread','sultanas','cinnamon','milk','double cream','eggs','sugar','nutmeg',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'25g/1oz','8 thin slices','50g/2oz','2 tsp','350ml/12fl','50ml/2fl oz','2 free-range','25g/1oz','grated, to taste',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'https://cooking.nytimes.com/recipes/1018529-coq-au-vin',NULL,NULL,NULL);
INSERT INTO meals(strMeal,strDrinkAlternate,strCategory,strArea,strInstructions,strMealThumb,strTags,strYoutube,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient16,strIngredient17,strIngredient18,strIngredient19,strIngredient20,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure16,strMeasure17,strMeasure18,strMeasure19,strMeasure20,strSource,strImageSource,strCreativeCommonsConfirmed,dateModified) VALUES ('Beef Wellington',NULL,'Beef','British','Put the mushrooms into a food processor with some seasoning and pulse to a rough paste. Scrape the paste into a pan and cook over a high heat for about 10 mins, tossing frequently, to cook out the moisture from the mushrooms. Spread out on a plate to cool.
Heat in a frying pan and add a little olive oil. Season the beef and sear in the hot pan for 30 secs only on each side. (You don''t want to cook it at this stage, just colour it). Remove the beef from the pan and leave to cool, then brush all over with the mustard.
Lay a sheet of cling film on a work surface and arrange the Parma ham slices on it, in slightly overlapping rows. With a palette knife, spread the mushroom paste over the ham, then place the seared beef fillet in the middle. Keeping a tight hold of the cling film from the edge, neatly roll the Parma ham and mushrooms around the beef to form a tight barrel shape. Twist the ends of the cling film to secure. Chill for 15-20 mins to allow the beef to set and keep its shape.
Roll out the puff pastry on a floured surface to a large rectangle, the thickness of a £1 coin. Remove the cling film from the beef, then lay in the centre. Brush the surrounding pastry with egg yolk. Fold the ends over, the wrap the pastry around the beef, cutting off any excess. Turn over, so the seam is underneath, and place on a baking sheet. Brush over all the pastry with egg and chill for about 15 mins to let the pastry rest.
Heat the oven to 200C, 400F, gas 6.
Lightly score the pastry at 1cm intervals and glaze again with beaten egg yolk. Bake for 20 minutes, then lower the oven setting to 180C, 350F, gas 4 and cook for another 15 mins. Allow to rest for 10-15 mins before slicing and serving with the side dishes of your choice. The beef should still be pink in the centre when you serve it.','https://www.themealdb.com/images/media/meals/vvpprx1487325699.jpg','Meat,Stew','https://www.youtube.com/watch?v=FS8u1RBdf6I','mushrooms','English Mustard','Olive Oil','Beef Fillet','Parma ham','Puff Pastry','Flour','Egg Yolks',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'400g','1-2tbsp','Dash','750g piece','6-8 slices','500g','Dusting','2 Beaten',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'http://www.goodtoknow.co.uk/recipes/164868/Gordon-Ramsay-s-beef-Wellington',NULL,NULL,NULL);
INSERT INTO meals(strMeal,strDrinkAlternate,strCategory,strArea,strInstructions,strMealThumb,strTags,strYoutube,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient16,strIngredient17,strIngredient18,strIngredient19,strIngredient20,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure16,strMeasure17,strMeasure18,strMeasure19,strMeasure20,strSource,strImageSource,strCreativeCommonsConfirmed,dateModified) VALUES ('Baingan Bharta',NULL,'Vegetarian','Indian','Rinse the baingan (eggplant or aubergine) in water. Pat dry with a kitchen napkin. Apply some oil all over and
keep it for roasting on an open flame. You can also grill the baingan or roast in the oven. But then you won''t get
the smoky flavor of the baingan. Keep the eggplant turning after a 2 to 3 minutes on the flame, so that its evenly
cooked. You could also embed some garlic cloves in the baingan and then roast it.
2. Roast the aubergine till its completely cooked and tender. With a knife check the doneness. The knife should slid
easily in aubergines without any resistance. Remove the baingan and immerse in a bowl of water till it cools
down.
3. You can also do the dhungar technique of infusing charcoal smoky flavor in the baingan. This is an optional step.
Use natural charcoal for this method. Heat a small piece of charcoal on flame till it becomes smoking hot and red.
4. Make small cuts on the baingan with a knife. Place the red hot charcoal in the same plate where the roasted
aubergine is kept. Add a few drops of oil on the charcoal. The charcoal would begin to smoke.
5. As soon as smoke begins to release from the charcoal, cover the entire plate tightly with a large bowl. Allow the
charcoal smoke to get infused for 1 to 2 minutes. The more you do, the more smoky the baingan bharta will
become. I just keep for a minute. Alternatively, you can also do this dhungar method once the baingan bharta is
cooked, just like the way we do for Dal Tadka.
6. Peel the skin from the roasted and smoked eggplant.
7. Chop the cooked eggplant finely or you can even mash it.
8. In a kadai or pan, heat oil. Then add finely chopped onions and garlic.
9. Saute the onions till translucent. Don''t brown them.
10. Add chopped green chilies and saute for a minute.
11. Add the chopped tomatoes and mix it well.
12. Bhuno (saute) the tomatoes till the oil starts separating from the mixture.
13. Now add the red chili powder. Stir and mix well.
14. Add the chopped cooked baingan.
15. Stir and mix the chopped baingan very well with the onion­tomato masala mixture.
16. Season with salt. Stir and saute for some more 4 to 5 minutes more.
17. Finally stir in the coriander leaves with the baingan bharta or garnish it with them. Serve Baingan Bharta with
phulkas, rotis or chapatis. It goes well even with bread, toasted or grilled bread and plain rice or jeera rice.','https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg','Spicy,Bun,Calorific','https://www.youtube.com/watch?v=-84Zz2EP4h4','Aubergine','Onion','Tomatoes','Garlic','Green Chili','Red Chili Powder','Oil','Coriander Leaves','salt',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1 large','½ cup','1 cup','6 cloves','1','¼ teaspoon','1.5 tablespoon','1 tablespoon chopped','as required',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'http://www.vegrecipesofindia.com/baingan-bharta-recipe-punjabi-baingan-bharta-recipe/',NULL,NULL,NULL);
INSERT INTO meals(strMeal,strDrinkAlternate,strCategory,strArea,strInstructions,strMealThumb,strTags,strYoutube,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient16,strIngredient17,strIngredient18,strIngredient19,strIngredient20,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure16,strMeasure17,strMeasure18,strMeasure19,strMeasure20,strSource,strImageSource,strCreativeCommonsConfirmed,dateModified) VALUES ('Beef Brisket Pot Roast',NULL,'Beef','American','1 Prepare the brisket for cooking: On one side of the brisket there should be a layer of fat, which you want. If there are any large chunks of fat, cut them off and discard them. Large pieces of fat will not be able to render out completely.
Using a sharp knife, score the fat in parallel lines, about 3/4-inch apart. Slice through the fat, not the beef. Repeat in the opposite direction to make a cross-hatch pattern.
Salt the brisket well and let it sit at room temperature for 30 minutes.

2 Sear the brisket: You''ll need an oven-proof, thick-bottomed pot with a cover, or Dutch oven, that is just wide enough to hold the brisket roast with a little room for the onions.
Pat the brisket dry and place it, fatty side down, into the pot and place it on medium high heat. Cook for 5-8 minutes, lightly sizzling, until the fat side is nicely browned. (If the roast seems to be cooking too fast, turn the heat down to medium. You want a steady sizzle, not a raging sear.)
Turn the brisket over and cook for a few minutes more to brown the other side.

3 Sauté the onions and garlic: When the brisket has browned, remove it from the pot and set aside. There should be a couple tablespoons of fat rendered in the pot, if not, add some olive oil.
Add the chopped onions and increase the heat to high. Sprinkle a little salt on the onions. Sauté, stirring often, until the onions are lightly browned, 5-8 minutes. Stir in the garlic and cook 1-2 more minutes.

4 Return brisket to pot, add herbs, stock, bring to simmer, cover, cook in oven: Preheat the oven to 300°F. Use kitchen twine to tie together the bay leaves, rosemary and thyme.
Move the onions and garlic to the sides of the pot and nestle the brisket inside. Add the beef stock and the tied-up herbs. Bring the stock to a boil on the stovetop.
Cover the pot, place the pot in the 300°F oven and cook for 3 hours. Carefully flip the brisket every hour so it cooks evenly.

5 Add carrots, continue to cook: After 3 hours, add the carrots. Cover the pot and cook for 1 hour more, or until the carrots are cooked through and the brisket is falling-apart tender.
6 Remove brisket to cutting board, tent with foil: When the brisket is falling-apart tender, take the pot out of the oven and remove the brisket to a cutting board. Cover it with foil. Pull out and discard the herbs.
7 Make sauce (optional): At this point you have two options. You can serve as is, or you can make a sauce with the drippings and some of the onions. If you serve as is, skip this step.
To make a sauce, remove the carrots and half of the onions, set aside and cover them with foil. Pour the ingredients that are remaining into the pot into a blender, and purée until smooth. If you want, add 1 tablespoon of mustard to the mix. Put into a small pot and keep warm.
8 Slice the meat across the grain: Notice the lines of the muscle fibers of the roast. This is the "grain" of the meat. Slice the meat perpendicular to these lines, or across the grain (cutting this way further tenderizes the meat), in 1/4-inch to 1/2-inch slices.
Serve with the onions, carrots and gravy. Serve with mashed, roasted or boiled potatoes, egg noodles or polenta.','https://www.themealdb.com/images/media/meals/ursuup1487348423.jpg','Meat','https://www.youtube.com/watch?v=gh48wM6bPWQ','Beef Brisket','Salt','Onion','Garlic','Thyme','Rosemary','Bay Leaves','beef stock','Carrots','Mustard','Potatoes',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'4-5 pound','Dash','3','5 cloves','1 Sprig','1 sprig','4','2 cups','3 Large','1 Tbsp','4 Mashed',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'http://www.simplyrecipes.com/recipes/beef_brisket_pot_roast/',NULL,NULL,NULL);

INSERT INTO meals(strMeal,strDrinkAlternate,strCategory,strArea,strInstructions,strMealThumb,strTags,strYoutube,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient16,strIngredient17,strIngredient18,strIngredient19,strIngredient20,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure16,strMeasure17,strMeasure18,strMeasure19,strMeasure20,strSource,strImageSource,strCreativeCommonsConfirmed,dateModified) VALUES ('Beef Caldereta',NULL,'Beef','Filipino','0.	Heat oil in a cooking pot. Saute onion and garlic until onion softens
1.	Add beef. Saute until the outer part turns light brown.
2.	Add soy sauce. Pour tomato sauce and water. Let boil.
3.	Add Knorr Beef Cube. Cover the pressure cooker. Cook for 30 minutes.
4.	Pan-fry carrot and potato until it browns. Set aside.
5.	Add chili pepper, liver spread and peanut butter. Stir.
6.	Add bell peppers, fried potato and carrot. Cover the pot. Continue cooking for 5 to 7 minutes.
7.	Season with salt and ground black pepper. Serve.','https://www.themealdb.com/images/media/meals/41cxjh1683207682.jpg',NULL,'https://www.youtube.com/watch?v=yI7hTz0ft5k','Beef','Beef Stock','Soy Sauce','Water','Green Pepper','Red Pepper','Potatoes','Carrots','Tomato Puree','Peanut Butter','Chilli Powder','Onion','Garlic','Olive Oil',NULL,NULL,NULL,NULL,NULL,NULL,'2kg cut cubes','1','1 tbs','2 cups','1 sliced','1 sliced','1 sliced','1 sliced','8 ounces','3  tablespoons','5','1 chopped','5 cloves','3 tbs',NULL,NULL,NULL,NULL,NULL,NULL,'https://www.kawalingpinoy.com/beef-caldereta/',NULL,NULL,NULL);

INSERT INTO meals(strMeal,strDrinkAlternate,strCategory,strArea,strInstructions,strMealThumb,strTags,strYoutube,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient16,strIngredient17,strIngredient18,strIngredient19,strIngredient20,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure16,strMeasure17,strMeasure18,strMeasure19,strMeasure20,strSource,strImageSource,strCreativeCommonsConfirmed,dateModified) VALUES ('Chicken Enchilada Casserole',NULL,'Chicken','Mexican','Cut each chicken breast in about 3 pieces, so that it cooks faster and put it in a small pot. Pour Enchilada sauce over it and cook covered on low to medium heat until chicken is cooked through, about 20 minutes. No water is needed, the chicken will cook in the Enchilada sauce. Make sure you stir occasionally so that it doesn''t stick to the bottom.
Remove chicken from the pot and shred with two forks.
Preheat oven to 375 F degrees.
Start layering the casserole. Start with about ¼ cup of the leftover Enchilada sauce over the bottom of a baking dish. I used a longer baking dish, so that I can put 2 corn tortillas across. Place 2 tortillas on the bottom, top with ⅓ of the chicken and ⅓ of the remaining sauce. Sprinkle with ⅓ of the cheese and repeat starting with 2 more tortillas, then chicken, sauce, cheese. Repeat with last layer with the remaining ingredients, tortillas, chicken, sauce and cheese.
Bake for 20 to 30 minutes uncovered, until bubbly and cheese has melted and started to brown on top.
Serve warm.','https://www.themealdb.com/images/media/meals/qtuwxu1468233098.jpg','Casserole,Cheasy,Meat','https://www.youtube.com/watch?v=EtVkwVKLc_M','Enchilada sauce','shredded Monterey Jack cheese','corn tortillas','chicken breasts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'14 oz jar','3 Cups','6','2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


INSERT INTO meals(strMeal,strDrinkAlternate,strCategory,strArea,strInstructions,strMealThumb,strTags,strYoutube,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient16,strIngredient17,strIngredient18,strIngredient19,strIngredient20,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure16,strMeasure17,strMeasure18,strMeasure19,strMeasure20,strSource,strImageSource,strCreativeCommonsConfirmed,dateModified) VALUES ('Chicken Handi',NULL,'Chicken','Indian','Take a large pot or wok, big enough to cook all the chicken, and heat the oil in it. Once the oil is hot, add sliced onion and fry them until deep golden brown. Then take them out on a plate and set aside.
To the same pot, add the chopped garlic and sauté for a minute. Then add the chopped tomatoes and cook until tomatoes turn soft. This would take about 5 minutes.
Then return the fried onion to the pot and stir. Add ginger paste and sauté well.
Now add the cumin seeds, half of the coriander seeds and chopped green chillies. Give them a quick stir.
Next goes in the spices – turmeric powder and red chilli powder. Sauté the spices well for couple of minutes.
Add the chicken pieces to the wok, season it with salt to taste and cook the chicken covered on medium-low heat until the chicken is almost cooked through. This would take about 15 minutes. Slowly sautéing the chicken will enhance the flavor, so do not expedite this step by putting it on high heat.
When the oil separates from the spices, add the beaten yogurt keeping the heat on lowest so that the yogurt doesn’t split. Sprinkle the remaining coriander seeds and add half of the dried fenugreek leaves. Mix well.
Finally add the cream and give a final mix to combine everything well.
Sprinkle the remaining kasuri methi and garam masala and serve the chicken handi hot with naan or rotis. Enjoy!','https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg',NULL,'https://www.youtube.com/watch?v=IO0issT0Rmc','Chicken','Onion','Tomatoes','Garlic','Ginger paste','Vegetable oil','Cumin seeds','Coriander seeds','Turmeric powder','Chilli powder','Green chilli','Yogurt','Cream','fenugreek','Garam masala','Salt',NULL,NULL,NULL,NULL,'1.2 kg','5 thinly sliced','2 finely chopped','8 cloves chopped','1 tbsp','¼ cup','2 tsp','3 tsp','1 tsp','1 tsp','2','1 cup','¾ cup','3 tsp Dried','1 tsp','To taste',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO meals(strMeal,strDrinkAlternate,strCategory,strArea,strInstructions,strMealThumb,strTags,strYoutube,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient16,strIngredient17,strIngredient18,strIngredient19,strIngredient20,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure16,strMeasure17,strMeasure18,strMeasure19,strMeasure20,strSource,strImageSource,strCreativeCommonsConfirmed,dateModified) VALUES ('Chicken Alfredo Primavera',NULL,'Chicken','Italian','Heat 1 tablespoon of butter and 2 tablespoons of olive oil in a large skillet over medium-high heat. Season both sides of each chicken breast with seasoned salt and a pinch of pepper. Add the chicken to the skillet and cook for 5-7 minutes on each side, or until cooked through.  While the chicken is cooking, bring a large pot of water to a boil. Season the boiling water with a few generous pinches of kosher salt. Add the pasta and give it a stir. Cook, stirring occasionally, until al dente, about 12 minutes. Reserve 1/2 cup of  pasta water before draining the pasta.  Remove the chicken from the pan and transfer it to a cutting board; allow it to rest. Turn the heat down to medium and dd the remaining 1 tablespoon of butter and olive oil to the same pan you used to cook the chicken. Add the veggies (minus the garlic) and red pepper flakes to the pan and stir to coat with the oil and butter (refrain from seasoning with salt until the veggies are finished browning). Cook, stirring often, until the veggies are tender, about 5 minutes. Add the garlic and a generous pinch of salt and pepper to the pan and cook for 1 minute.  Deglaze the pan with the white wine. Continue to cook until the wine has reduced by half, about 3 minutes. Stir in the milk, heavy cream, and reserved pasta water. Bring the mixture to a gentle boil and allow to simmer and reduce for 2-3 minutes. Turn off the heat and add the Parmesan cheese and cooked pasta. Season with salt and pepper to taste. Garnish with Parmesan cheese and chopped parsley, if desired.','https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg','Pasta,Meat,Dairy','https://www.youtube.com/watch?v=qCIbq8HywpQ','Butter','Olive Oil','Chicken','Salt','Squash','Broccoli','mushrooms','Pepper','onion','garlic','red pepper flakes','white wine','milk','heavy cream','Parmesan cheese','bowtie pasta','Salt','Pepper','Parsley',NULL,'2 tablespoons','3 tablespoons','5 boneless','1 teaspoon','1 cut into 1/2-inch cubes','1 Head chopped','8-ounce sliced','1 red','1 chopped','3 cloves','1/2 teaspoon','1/2 cup','1/2 cup','1/2 cup','1 cup grated','16 ounces','pinch','pinch','chopped',NULL,NULL,NULL,NULL,NULL);
INSERT INTO meals(strMeal,strDrinkAlternate,strCategory,strArea,strInstructions,strMealThumb,strTags,strYoutube,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient16,strIngredient17,strIngredient18,strIngredient19,strIngredient20,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure16,strMeasure17,strMeasure18,strMeasure19,strMeasure20,strSource,strImageSource,strCreativeCommonsConfirmed,dateModified) VALUES ('Chicken Fajita Mac and Cheese',NULL,'Chicken','American','Fry your onion, peppers and garlic in olive oil until nicely translucent. Make a well in your veg and add your chicken. Add your seasoning and salt. Allow to colour slightly.
Add your cream, stock and macaroni.
Cook on low for 20 minutes. Add your cheeses, stir to combine.
Top with roasted peppers and parsley.','https://www.themealdb.com/images/media/meals/qrqywr1503066605.jpg','Pasta,Cheasy,Meat','https://www.youtube.com/watch?v=bwTSmLTZKNg','macaroni','chicken stock','heavy cream','fajita seasoning','salt','chicken breast','olive oil','onion','red pepper','garlic','cheddar cheese','parsley',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'500g','2 cups','1/2 cup','1 packet','1 tsp','3 diced','2 tbsp','1 small finely diced','2 finely diced','2 cloves minced','1 cup','garnish chopped',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'http://twistedfood.co.uk/chicken-fajita-mac-n-cheese/',NULL,NULL,NULL);

INSERT INTO meals(strMeal,strDrinkAlternate,strCategory,strArea,strInstructions,strMealThumb,strTags,strYoutube,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient16,strIngredient17,strIngredient18,strIngredient19,strIngredient20,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure16,strMeasure17,strMeasure18,strMeasure19,strMeasure20,strSource,strImageSource,strCreativeCommonsConfirmed,dateModified) VALUES ('Cashew Ghoriba Biscuits',NULL,'Dessert','Tunisian','Preheat the oven at 180 C / Gas 4. Line a baking tray with greaseproof paper.
In a bowl, mix the cashews and icing sugar. Add the egg yolks and orange blossom water and mix to a smooth homogeneous paste.
Take lumps of the cashew paste and shape into small balls. Roll the balls in icing sugar and transfer to the baking tray. Push an almond in the centre of each ghribia.
Bake until the biscuits are lightly golden, about 20 minutes. Keep an eye on them, they burn quickly.','https://www.themealdb.com/images/media/meals/t3r3ka1560461972.jpg',NULL,'https://www.youtube.com/watch?v=IqXEZUk4hWI','Cashew Nuts','Icing Sugar','Egg Yolks','Orange Blossom Water','Icing Sugar','Almonds',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'250g','100g','2','2 tbs','To Glaze','100g',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'http://allrecipes.co.uk/recipe/40152/cashew-ghoriba-biscuits.aspx',NULL,NULL,NULL);

INSERT INTO meals(strMeal,strDrinkAlternate,strCategory,strArea,strInstructions,strMealThumb,strTags,strYoutube,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strIngredient16,strIngredient17,strIngredient18,strIngredient19,strIngredient20,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strMeasure16,strMeasure17,strMeasure18,strMeasure19,strMeasure20,strSource,strImageSource,strCreativeCommonsConfirmed,dateModified) VALUES ('Chick-Fil-A Sandwich',NULL,'Chicken','American','Wrap the chicken loosely between plastic wrap and pound gently with the flat side of a meat tenderizer until about 1/2 inch thick all around.
Marinate in the pickle juice for 30 minutes to one hour (add a teaspoon of Tabasco sauce now for a spicy sandwich).
Beat the egg with the milk in a bowl.
Combine the flour, sugar, and spices in another bowl.
Dip the chicken pieces each into the egg on both sides, then coat in flour on both sides.
Heat the oil in a skillet (1/2 inch deep) to about 345-350.
Fry each cutlet for 2 minutes on each side, or until golden and cooked through.
Blot on paper and serve on toasted buns with pickle slices.','https://www.themealdb.com/images/media/meals/sbx7n71587673021.jpg',NULL,'https://www.youtube.com/watch?v=1WDesu7bUDM','Chicken Breast','Pickle Juice','Egg','Milk','Flour','Icing Sugar','Paprika','Salt','Black Pepper','Garlic Powder','Celery Salt','Cayenne Pepper','Olive Oil','Sesame Seed Burger Buns',NULL,NULL,NULL,NULL,NULL,NULL,'1','1/4 cup','1','1/4 cup','1/2 cup','1 tbs','1/2 tsp','1/2 tsp','1/4 tsp','1/4 tsp','1/4 tsp','1/2 tsp','1 cup','1',NULL,NULL,NULL,NULL,NULL,NULL,'https://hilahcooking.com/chick-fil-a-copycat/',NULL,NULL,NULL);
